# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bittorrent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bittorrent.proto',
  package='bittorrent',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x62ittorrent.proto\x12\nbittorrent\"\x07\n\x05Vacio\"/\n\x08InfoNodo\x12\x11\n\tip_puerto\x18\x01 \x01(\t\x12\x10\n\x08\x61rchivos\x18\x02 \x03(\t\",\n\nAckTracker\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\")\n\x0f\x42usquedaArchivo\x12\x16\n\x0enombre_archivo\x18\x01 \x01(\t\"\'\n\nListaPeers\x12\x19\n\x11peers_con_archivo\x18\x01 \x03(\t\"=\n\rPeticionChunk\x12\x16\n\x0enombre_archivo\x18\x01 \x01(\t\x12\x14\n\x0cindice_chunk\x18\x02 \x01(\x05\"D\n\tDataChunk\x12\x12\n\nencontrado\x18\x01 \x01(\x08\x12\r\n\x05\x64\x61tos\x18\x02 \x01(\x0c\x12\x14\n\x0cindice_chunk\x18\x03 \x01(\x05\"2\n\x0b\x45stadoSwarm\x12#\n\x05nodos\x18\x01 \x03(\x0b\x32\x14.bittorrent.InfoNodo\"Y\n\x0bInfoArchivo\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x14\n\x0ctamano_bytes\x18\x02 \x01(\x03\x12\x14\n\x0ctotal_chunks\x18\x03 \x01(\x05\x12\x0e\n\x06\x65xiste\x18\x04 \x01(\x08\x32\xd7\x01\n\x0eTrackerService\x12=\n\rRegistrarNodo\x12\x14.bittorrent.InfoNodo\x1a\x16.bittorrent.AckTracker\x12\x44\n\rBuscarArchivo\x12\x1b.bittorrent.BusquedaArchivo\x1a\x16.bittorrent.ListaPeers\x12@\n\x12ObtenerEstadoSwarm\x12\x11.bittorrent.Vacio\x1a\x17.bittorrent.EstadoSwarm2\x9c\x01\n\nP2PService\x12\x42\n\x0eSolicitarChunk\x12\x19.bittorrent.PeticionChunk\x1a\x15.bittorrent.DataChunk\x12J\n\x12ObtenerInfoArchivo\x12\x1b.bittorrent.BusquedaArchivo\x1a\x17.bittorrent.InfoArchivob\x06proto3'
)




_VACIO = _descriptor.Descriptor(
  name='Vacio',
  full_name='bittorrent.Vacio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_INFONODO = _descriptor.Descriptor(
  name='InfoNodo',
  full_name='bittorrent.InfoNodo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_puerto', full_name='bittorrent.InfoNodo.ip_puerto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='archivos', full_name='bittorrent.InfoNodo.archivos', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=88,
)


_ACKTRACKER = _descriptor.Descriptor(
  name='AckTracker',
  full_name='bittorrent.AckTracker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exito', full_name='bittorrent.AckTracker.exito', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='bittorrent.AckTracker.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=134,
)


_BUSQUEDAARCHIVO = _descriptor.Descriptor(
  name='BusquedaArchivo',
  full_name='bittorrent.BusquedaArchivo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre_archivo', full_name='bittorrent.BusquedaArchivo.nombre_archivo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=177,
)


_LISTAPEERS = _descriptor.Descriptor(
  name='ListaPeers',
  full_name='bittorrent.ListaPeers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers_con_archivo', full_name='bittorrent.ListaPeers.peers_con_archivo', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=218,
)


_PETICIONCHUNK = _descriptor.Descriptor(
  name='PeticionChunk',
  full_name='bittorrent.PeticionChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre_archivo', full_name='bittorrent.PeticionChunk.nombre_archivo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indice_chunk', full_name='bittorrent.PeticionChunk.indice_chunk', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=281,
)


_DATACHUNK = _descriptor.Descriptor(
  name='DataChunk',
  full_name='bittorrent.DataChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encontrado', full_name='bittorrent.DataChunk.encontrado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datos', full_name='bittorrent.DataChunk.datos', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indice_chunk', full_name='bittorrent.DataChunk.indice_chunk', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=351,
)


_ESTADOSWARM = _descriptor.Descriptor(
  name='EstadoSwarm',
  full_name='bittorrent.EstadoSwarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodos', full_name='bittorrent.EstadoSwarm.nodos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=403,
)


_INFOARCHIVO = _descriptor.Descriptor(
  name='InfoArchivo',
  full_name='bittorrent.InfoArchivo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='bittorrent.InfoArchivo.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tamano_bytes', full_name='bittorrent.InfoArchivo.tamano_bytes', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_chunks', full_name='bittorrent.InfoArchivo.total_chunks', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='existe', full_name='bittorrent.InfoArchivo.existe', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=494,
)

_ESTADOSWARM.fields_by_name['nodos'].message_type = _INFONODO
DESCRIPTOR.message_types_by_name['Vacio'] = _VACIO
DESCRIPTOR.message_types_by_name['InfoNodo'] = _INFONODO
DESCRIPTOR.message_types_by_name['AckTracker'] = _ACKTRACKER
DESCRIPTOR.message_types_by_name['BusquedaArchivo'] = _BUSQUEDAARCHIVO
DESCRIPTOR.message_types_by_name['ListaPeers'] = _LISTAPEERS
DESCRIPTOR.message_types_by_name['PeticionChunk'] = _PETICIONCHUNK
DESCRIPTOR.message_types_by_name['DataChunk'] = _DATACHUNK
DESCRIPTOR.message_types_by_name['EstadoSwarm'] = _ESTADOSWARM
DESCRIPTOR.message_types_by_name['InfoArchivo'] = _INFOARCHIVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vacio = _reflection.GeneratedProtocolMessageType('Vacio', (_message.Message,), {
  'DESCRIPTOR' : _VACIO,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.Vacio)
  })
_sym_db.RegisterMessage(Vacio)

InfoNodo = _reflection.GeneratedProtocolMessageType('InfoNodo', (_message.Message,), {
  'DESCRIPTOR' : _INFONODO,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.InfoNodo)
  })
_sym_db.RegisterMessage(InfoNodo)

AckTracker = _reflection.GeneratedProtocolMessageType('AckTracker', (_message.Message,), {
  'DESCRIPTOR' : _ACKTRACKER,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.AckTracker)
  })
_sym_db.RegisterMessage(AckTracker)

BusquedaArchivo = _reflection.GeneratedProtocolMessageType('BusquedaArchivo', (_message.Message,), {
  'DESCRIPTOR' : _BUSQUEDAARCHIVO,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.BusquedaArchivo)
  })
_sym_db.RegisterMessage(BusquedaArchivo)

ListaPeers = _reflection.GeneratedProtocolMessageType('ListaPeers', (_message.Message,), {
  'DESCRIPTOR' : _LISTAPEERS,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.ListaPeers)
  })
_sym_db.RegisterMessage(ListaPeers)

PeticionChunk = _reflection.GeneratedProtocolMessageType('PeticionChunk', (_message.Message,), {
  'DESCRIPTOR' : _PETICIONCHUNK,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.PeticionChunk)
  })
_sym_db.RegisterMessage(PeticionChunk)

DataChunk = _reflection.GeneratedProtocolMessageType('DataChunk', (_message.Message,), {
  'DESCRIPTOR' : _DATACHUNK,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.DataChunk)
  })
_sym_db.RegisterMessage(DataChunk)

EstadoSwarm = _reflection.GeneratedProtocolMessageType('EstadoSwarm', (_message.Message,), {
  'DESCRIPTOR' : _ESTADOSWARM,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.EstadoSwarm)
  })
_sym_db.RegisterMessage(EstadoSwarm)

InfoArchivo = _reflection.GeneratedProtocolMessageType('InfoArchivo', (_message.Message,), {
  'DESCRIPTOR' : _INFOARCHIVO,
  '__module__' : 'bittorrent_pb2'
  # @@protoc_insertion_point(class_scope:bittorrent.InfoArchivo)
  })
_sym_db.RegisterMessage(InfoArchivo)



_TRACKERSERVICE = _descriptor.ServiceDescriptor(
  name='TrackerService',
  full_name='bittorrent.TrackerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=497,
  serialized_end=712,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegistrarNodo',
    full_name='bittorrent.TrackerService.RegistrarNodo',
    index=0,
    containing_service=None,
    input_type=_INFONODO,
    output_type=_ACKTRACKER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BuscarArchivo',
    full_name='bittorrent.TrackerService.BuscarArchivo',
    index=1,
    containing_service=None,
    input_type=_BUSQUEDAARCHIVO,
    output_type=_LISTAPEERS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ObtenerEstadoSwarm',
    full_name='bittorrent.TrackerService.ObtenerEstadoSwarm',
    index=2,
    containing_service=None,
    input_type=_VACIO,
    output_type=_ESTADOSWARM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKERSERVICE)

DESCRIPTOR.services_by_name['TrackerService'] = _TRACKERSERVICE


_P2PSERVICE = _descriptor.ServiceDescriptor(
  name='P2PService',
  full_name='bittorrent.P2PService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=715,
  serialized_end=871,
  methods=[
  _descriptor.MethodDescriptor(
    name='SolicitarChunk',
    full_name='bittorrent.P2PService.SolicitarChunk',
    index=0,
    containing_service=None,
    input_type=_PETICIONCHUNK,
    output_type=_DATACHUNK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ObtenerInfoArchivo',
    full_name='bittorrent.P2PService.ObtenerInfoArchivo',
    index=1,
    containing_service=None,
    input_type=_BUSQUEDAARCHIVO,
    output_type=_INFOARCHIVO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_P2PSERVICE)

DESCRIPTOR.services_by_name['P2PService'] = _P2PSERVICE

# @@protoc_insertion_point(module_scope)
