# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bittorrent_pb2 as bittorrent__pb2


class TrackerServiceStub(object):
    """=============================================================
    SERVICIO 1: El Tracker (El "Directorio")
    =============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarNodo = channel.unary_unary(
                '/bittorrent.TrackerService/RegistrarNodo',
                request_serializer=bittorrent__pb2.InfoNodo.SerializeToString,
                response_deserializer=bittorrent__pb2.AckTracker.FromString,
                )
        self.BuscarArchivo = channel.unary_unary(
                '/bittorrent.TrackerService/BuscarArchivo',
                request_serializer=bittorrent__pb2.BusquedaArchivo.SerializeToString,
                response_deserializer=bittorrent__pb2.ListaPeers.FromString,
                )
        self.ObtenerEstadoSwarm = channel.unary_unary(
                '/bittorrent.TrackerService/ObtenerEstadoSwarm',
                request_serializer=bittorrent__pb2.Vacio.SerializeToString,
                response_deserializer=bittorrent__pb2.EstadoSwarm.FromString,
                )


class TrackerServiceServicer(object):
    """=============================================================
    SERVICIO 1: El Tracker (El "Directorio")
    =============================================================
    """

    def RegistrarNodo(self, request, context):
        """Se usa al inicio y periódicamente (heartbeat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarArchivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerEstadoSwarm(self, request, context):
        """(Opcional) Para ver la lista global en la consola del Tracker (punto 2 del PDF)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarNodo': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarNodo,
                    request_deserializer=bittorrent__pb2.InfoNodo.FromString,
                    response_serializer=bittorrent__pb2.AckTracker.SerializeToString,
            ),
            'BuscarArchivo': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarArchivo,
                    request_deserializer=bittorrent__pb2.BusquedaArchivo.FromString,
                    response_serializer=bittorrent__pb2.ListaPeers.SerializeToString,
            ),
            'ObtenerEstadoSwarm': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstadoSwarm,
                    request_deserializer=bittorrent__pb2.Vacio.FromString,
                    response_serializer=bittorrent__pb2.EstadoSwarm.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bittorrent.TrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackerService(object):
    """=============================================================
    SERVICIO 1: El Tracker (El "Directorio")
    =============================================================
    """

    @staticmethod
    def RegistrarNodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.TrackerService/RegistrarNodo',
            bittorrent__pb2.InfoNodo.SerializeToString,
            bittorrent__pb2.AckTracker.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuscarArchivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.TrackerService/BuscarArchivo',
            bittorrent__pb2.BusquedaArchivo.SerializeToString,
            bittorrent__pb2.ListaPeers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerEstadoSwarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.TrackerService/ObtenerEstadoSwarm',
            bittorrent__pb2.Vacio.SerializeToString,
            bittorrent__pb2.EstadoSwarm.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class P2PServiceStub(object):
    """=============================================================
    SERVICIO 2: El Nodo P2P (Transferencia de archivos)
    =============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolicitarChunk = channel.unary_unary(
                '/bittorrent.P2PService/SolicitarChunk',
                request_serializer=bittorrent__pb2.PeticionChunk.SerializeToString,
                response_deserializer=bittorrent__pb2.DataChunk.FromString,
                )
        self.ObtenerInfoArchivo = channel.unary_unary(
                '/bittorrent.P2PService/ObtenerInfoArchivo',
                request_serializer=bittorrent__pb2.BusquedaArchivo.SerializeToString,
                response_deserializer=bittorrent__pb2.InfoArchivo.FromString,
                )


class P2PServiceServicer(object):
    """=============================================================
    SERVICIO 2: El Nodo P2P (Transferencia de archivos)
    =============================================================
    """

    def SolicitarChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerInfoArchivo(self, request, context):
        """NUEVO: Preguntar metadatos del archivo, para que sepa cuánto pesan los archivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolicitarChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarChunk,
                    request_deserializer=bittorrent__pb2.PeticionChunk.FromString,
                    response_serializer=bittorrent__pb2.DataChunk.SerializeToString,
            ),
            'ObtenerInfoArchivo': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerInfoArchivo,
                    request_deserializer=bittorrent__pb2.BusquedaArchivo.FromString,
                    response_serializer=bittorrent__pb2.InfoArchivo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bittorrent.P2PService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class P2PService(object):
    """=============================================================
    SERVICIO 2: El Nodo P2P (Transferencia de archivos)
    =============================================================
    """

    @staticmethod
    def SolicitarChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.P2PService/SolicitarChunk',
            bittorrent__pb2.PeticionChunk.SerializeToString,
            bittorrent__pb2.DataChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerInfoArchivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.P2PService/ObtenerInfoArchivo',
            bittorrent__pb2.BusquedaArchivo.SerializeToString,
            bittorrent__pb2.InfoArchivo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
